segundas/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url('', include('segundasapp.urls')),
    url(r'^admin/', admin.site.urls),
]

segundasapp/urls.py
#Imports.
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?:contacto)/$', views.contacto, name='contacto'),
    url(r'^(?:get_mensaje_contacto)/$', views.get_mensaje_contacto, name='get_mensaje_contacto'),
    url(r'^(?:venta_segundas)/$', views.venta_segundas, name='venta_segundas'),
    url(r'^(?:filtro_segundas)/$', views.filtro_segundas, name='filtro_segundas'),
    url(r'^(?:ordenar_segundas)/$', views.ordenar_segundas, name='ordenar_segundas'),
    url(r'^(?:page_segundas)/$', views.page_segundas, name='page_segundas'),
    url(r'^(?:google5a135354c3e98127)/$', views.google5a135354c3e98127, name='google5a135354c3e98127'),
    # url(r'^(?:prueba)/$', views.prueba, name='prueba'),
    url(r'^(?:get_contacto_segunda)/$', views.get_contacto_segunda, name='get_contacto_segunda'),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

segundasapp/models.py
from __future__ import unicode_literals
from djmoney.models.fields import MoneyField
from django.db import models
# Create your models here.
class Attachment(models.Model):
    fileattach = models.FileField(upload_to='segundasapp/static/segundasapp/imagenescontacto')
    fichacontacto = models.ForeignKey('Contacto', related_name='images', blank=True, null=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.filename

    @property
    def filename(self):
        return self.fileattach.name.rsplit('/', 1)[-1]

class Contacto(models.Model):
    fecha = models.DateField()
    titulo = models.CharField( max_length=100)

class Segunda(models.Model):
    #idsegunda = models.AutoField()  # Field name made lowercase.
    CAT_SEG = (
        ('A', 'Acero'),
        ('M', 'Material de Construcción'),
        ('V', 'Varilla'),
        ('O', 'Otros'),
    )
    titulo = models.CharField( max_length=100)  # Field name made lowercase.
    contenido = models.TextField()  # Field name made lowercase.
    fecha = models.DateField()
    precio = MoneyField(max_digits=10, decimal_places=2, default_currency='MXN')
    categoria = models.CharField(max_length=1, choices=CAT_SEG)
    def __str__(self):
        return str(self.titulo)

class Image(models.Model):
    fileimage = models.FileField('File', upload_to='segundasapp/static/segundasapp/imagenesegundas')
    gallery = models.ForeignKey('Segunda', related_name='images', blank=True, null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.filename

    @property
    def filename(self):
        return self.fileimage.name.rsplit('/', 1)[-1]

segundasapp/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from multiuploadform.fields import MultiImageField
from django.utils import html

class ContactoMail(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nombre','type':'text','class':'validate'}),max_length=100)
    apellido_contacto = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Apellidos','type':'text','class':'validate'}),max_length=100)
    telefono_contacto = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '55-55-55-55','type':'tel','class':'validate'}),max_length=14,min_length=8)
    email_contacto = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'ejemplo@ejemplo.com','type':'email','class':'validate'}),max_length = 100)
    titulo_contacto = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Título','type':'text','class':'validate'}),max_length=100,required=False)
    textarea_contacto = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Breve descripción'}),max_length = 500)
    precio_contacto = forms.FloatField(widget=forms.NumberInput(attrs={'placeholder': 'Desde','type': 'number','min':'0','max':'100000000','step':'.01','value':'0','name':'min'}),required=False)
    #imagenes_contacto = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}),required=False)
    imagenes_contacto = MultiImageField(min_num=1, max_num=3, max_file_size=1024*1024*5,required=False)

CAT_CHOICES= [
    ('T', 'Todos'),
    ('A', 'Acero'),
    ('M', 'Material de Construcción'),
    ('O', 'Otros'),
    ('V', 'Varilla'),
    ]

class BusquedaSegundas(forms.Form):
    titulo_busqueda = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Título o palabra clave','type':'text','class':'validate'}),max_length=100,required=False)
    precio_busqueda_min = forms.FloatField(widget=forms.NumberInput(attrs={'placeholder': 'Desde','type': 'number','min':'0','max':'100000000','step':'.01','value':'0','name':'min'}),required=False)
    precio_busqueda_max = forms.FloatField(widget=forms.NumberInput(attrs={'placeholder': 'Hasta','type': 'number','min':'0','max':'100000000','step':'.01','value':'0','name':'max'}),required=False)
    categoria_busqueda= forms.CharField(label='Seleccione una categoría', widget=forms.Select(choices=CAT_CHOICES))

class ContactoSegunda(forms.Form):
    nombre_segunda = forms.CharField(widget=forms.TextInput(attrs={'type':'text','class':'validate'}),max_length=100)
    apellido_segunda = forms.CharField(widget=forms.TextInput(attrs={'type':'text','class':'validate'}),max_length=100)
    telefono_segunda = forms.CharField(widget=forms.TextInput(attrs={'type':'tel','class':'validate'}),max_length=14,min_length=8)
    email_segunda = forms.EmailField(widget=forms.TextInput(attrs={'type':'email','class':'validate'}),max_length = 100)
    textarea_segunda = forms.CharField(widget=forms.Textarea(attrs={'class':'materialize-textarea'}),max_length = 500,required=False)

segundasapp/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
import json
import time
import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.template import Context
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage
from django.middleware.csrf import get_token
from django.views.generic.edit import FormView
#Importar formas.
from .forms import *
from .models import *
import math
#limite paginacion
lim = 6
correocontacto="acervantes@grupobsv.com.mx"
# Create your views here.
def index(request):
    segundas = Segunda.objects.filter().order_by('-fecha')
    cuenta = math.ceil(segundas.count()/3)
    segundas = segundas[:3]
    formseg = ContactoSegunda(request.POST)
    return render(request, 'segundasapp/index.html',{'segundas':segundas,\
    'count':range(cuenta)})

def google5a135354c3e98127(request):
    return render(request, 'segundasapp/google5a135354c3e98127.html')
#Para contacto.
def contacto(request):
    form = ContactoMail(request.POST,request.FILES)
    return render(request, 'segundasapp/contacto.html',{'form':form})
    #Para forma de contacto.

def prueba(request):
    print("plueba")
    return render(request, 'segundasapp/prueba.html')

#obtener datos de interesado en post de segunda
def get_contacto_segunda(request):
    form = ContactoSegunda(request.POST)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # check whether it's valid:
        body = json.loads(request.POST.get('formData'))
        formdict = {}
        for i in body:
            formdict[i['name']]= i['value']
        # datos contacto segunda
        nombre = formdict['nombre_segunda']
        apellido = formdict['apellido_segunda']
        telefono = formdict['telefono_segunda']
        email = formdict['email_segunda']
        observaciones = formdict['textarea_segunda']
        # datos segunda
        titulo = formdict['titulo_segunda']
        contenido = formdict['contenido_segunda']
        llave = formdict['llave_segunda']
        precio = formdict['precio_segunda']

        ctx = {
            'nombre': nombre,
            'apellido': apellido,
            'telefono': telefono,
            'correo': email,
            'observaciones': observaciones,
            'contenido': contenido,
            'precio': precio,
            'llave': llave,
            'segunda': titulo
        }
        # enviar datos de correo
        subject = "Segundas"
        to = [correocontacto]
        from_email = 'acervantesbsv@gmail.com'
        message = render_to_string('segundasapp/email.html',ctx)
        msg = EmailMessage(subject, message, to=to, from_email=from_email)
        msg.content_subtype = 'html'
        if(msg.send()):
            print("sent")
        # redirect to a new URL:
        return HttpResponse("éxito")
    else:
        print("No valida!")
        return HttpResponse('error')

def get_mensaje_contacto(request):
    # create a form instance and populate it with data from the request:
    form = ContactoMail(request.POST)
    nombre = request.POST.get("first_name")
    print(nombre)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # check whether it's valid:
    # if form.is_valid():
        nombre = request.POST.get("first_name")
        apellido = request.POST.get("last_name")
        telefono = request.POST.get("phone")
        email = request.POST.get("email")
        texto = request.POST.get("textarea_contacto")
        titulo = request.POST.get("titulo_contacto")
        precio = request.POST.get("precio_contacto")
        #redactar correo
        ctx = {
            'nombre': nombre,
            'apellido': apellido,
            'telefono': telefono,
            'correo': email,
            'texto': texto,
            'titulo':titulo,
            'precio':precio
        }
        #info correo
        subject = "Segundas"
        to = [correocontacto]
        from_email = 'acervantesbsv@gmail.com'
        message = render_to_string('segundasapp/email-contacto.html',ctx)
        msg = EmailMessage(subject, message, to=to, from_email=from_email)
        msg.content_subtype = 'html'
        c = Contacto.objects.create(titulo=titulo,fecha=datetime.datetime.now())
        #procesar imagenes enviadas
        if(len(request.FILES.getlist('imagenes_contacto'))!= 0):
            files = request.FILES.getlist('imagenes_contacto')

            for fileach in files:
                a = Attachment.objects.create(fileattach=fileach,fichacontacto=c)
                print(a.fileattach.name)
                msg.attach_file(a.fileattach.name)
        else:
            print("no se subieron archivos")

        if(msg.send()):
            c.delete()
            print("sent")
        else:
            print("no se envio:")
            print(c.pk)

        # redirect to a new URL:
        print("Valido!")
        return HttpResponseRedirect('/')
    # else:
    #     print("No valida!")
    #     return HttpResponseRedirect('/contacto/')
    # if a GET (or any other method) we'll create a blank form
    #else:
    #    form = ContactoMail()
    return HttpResponseRedirect('/contacto/')

def venta_segundas(request):
    segundas = Segunda.objects.filter().order_by('titulo')
    cuenta = math.ceil(segundas.count()/lim)
    segundas = segundas[:lim]
    form = BusquedaSegundas(request.POST)
    formseg = ContactoSegunda(request.POST)
    return render(request,'segundasapp/venta_segundas.html',{'form':form,'formseg':formseg,\
                  'segundas':segundas,'count':range(cuenta)})

def ordenar_segundas(request):
    if request.method == 'GET':
        body = json.loads(request.GET.get('formData'))
        ordenar = request.GET.get('ordenar')
        asc = request.GET.get('asc')
        print(asc)
        formdict = {}
        for i in body:
            formdict[i['name']]= i['value']
        if(formdict['categoria_busqueda']=='T'):
            segundas = Segunda.objects.filter(Q(titulo__icontains=formdict['titulo_busqueda']) \
            | Q(titulo__icontains=formdict['titulo_busqueda'])).order_by('titulo')
            #print(float(formdict['precio_busqueda_max']))
            if(float(formdict['precio_busqueda_max'])!=0):
                segundas = segundas.filter(precio__gte=formdict['precio_busqueda_min'],\
                precio__lte=formdict['precio_busqueda_max']).order_by('titulo')
        else:
            segundas = Segunda.objects.filter(Q(titulo__icontains=formdict['titulo_busqueda']) \
            | Q(contenido__icontains=formdict['titulo_busqueda']), \
            Q(categoria__exact=formdict['categoria_busqueda'])).order_by('titulo')
            if(float(formdict['precio_busqueda_max'])!=0):
                segundas = segundas.filter(precio__gte=formdict['precio_busqueda_min'],\
                precio__lte=formdict['precio_busqueda_max']).order_by('titulo')
        if(ordenar=='fecha'):
            if(int(asc)==1):
                segundas = segundas.order_by('-fecha')
            else:
                if(int(asc)==0):
                    segundas = segundas.order_by('fecha')
        else:
            if(int(asc)==1):
                segundas = segundas.order_by('-precio')
            else:
                if(int(asc)==0):
                    segundas = segundas.order_by('precio')
        cuenta = math.ceil(segundas.count()/lim)
        segundas = segundas[:lim]
        formseg = ContactoSegunda(request.POST)
        csrf_token_value = get_token(request);
        paginate = render_to_string('segundasapp/paginate.html',{'count':range(cuenta)})
        segundas = render_to_string('segundasapp/filtro_segundas.html',\
        {'segundas':segundas,'formseg':formseg,'token':csrf_token_value})
        jsonData = {}
        jsonData['segundas'] = segundas
        jsonData['paginate'] = paginate
        jsonData = json.dumps(jsonData)
        return HttpResponse(jsonData)
    else:
        return HttpResponse("error")

def filtro_segundas(request):
    if request.method == 'GET':
        body = json.loads(request.GET.get('formData'))
        formdict = {}
        for i in body:
            formdict[i['name']]= i['value']
            print(i['name'])
            print(i['value'])

        if(formdict['categoria_busqueda']=='T'):
            segundas = Segunda.objects.filter(Q(titulo__icontains=formdict['titulo_busqueda']) \
            | Q(titulo__icontains=formdict['titulo_busqueda'])).order_by('titulo')
            #print(float(formdict['precio_busqueda_max']))
            if(float(formdict['precio_busqueda_max'])!=0):
                segundas = segundas.filter(precio__gte=formdict['precio_busqueda_min'],\
                precio__lte=formdict['precio_busqueda_max']).order_by('titulo')
        else:
            segundas = Segunda.objects.filter(Q(titulo__icontains=formdict['titulo_busqueda']) \
            | Q(contenido__icontains=formdict['titulo_busqueda']), \
            Q(categoria__exact=formdict['categoria_busqueda'])).order_by('titulo')
            if(float(formdict['precio_busqueda_max'])!=0):
                segundas = segundas.filter(precio__gte=formdict['precio_busqueda_min'],\
                precio__lte=formdict['precio_busqueda_max']).order_by('titulo')
        cuenta = math.ceil(segundas.count()/lim)
        segundas = segundas[:lim]
        formseg = ContactoSegunda(request.POST)
        csrf_token_value = get_token(request);
        paginate = render_to_string('segundasapp/paginate.html',{'count':range(cuenta)})
        segundas = render_to_string('segundasapp/filtro_segundas.html',\
        {'segundas':segundas,'formseg':formseg,'token':csrf_token_value})
        jsonData = {}

segundasapp/templates/segundasapp/filtro_segundas.html
{% load static %}
{% for segunda in segundas %}
{% if forloop.first == true or forloop.counter|divisibleby:3 %}
    <div class="row">
      {% endif %}
      <div class="col l4 m6 s12">
        <div class="card">
          <div class="card-image" style="margin-bottom:1px;">
            <!-- Aqui empieza carrusel -->
             <div class="testcar" style="max-width:100%;max-height:200px">
               {% for imagen in segunda.images.all %}
                 <div class="option">
                     <img src="{{ imagen.fileimage.url|slice:"11:" }}" style="width:100%;height:200px;">
                 </div>
               {% endfor %}
                 <div class="prev_next">
                 </div>
             </div>
             <a class="btn-floating halfway-fab waves-effect waves-light modal-trigger columbiablue" href="#modal{{ forloop.counter }}">
               <i class="material-icons">add</i></a>
            <!-- <img src="/{{ segunda.imagen.url }}" style="width:300px;height:250px;"> -->
          </div>
          <div class="card-stacked">
          <div class="card-content" style="padding:0px;margin-left:10px;">
          <h6 style="font-weight:bold;"> {{ segunda.get_categoria_display }} </h6>
          <h6 style="font-weight:bold;">{{ segunda.titulo }}</h6>
          <h6>{{ segunda.fecha }}</h6>
          <h6>{{ segunda.precio }}</h6>
          <br>
        </div>
        <div id="modal{{ forloop.counter }}" class="modal modal-fixed-footer">
          <div  class="modal-content">
            <h4>{{ segunda.titulo }}</h4>
            <p>{{ segunda.contenido }}</p>
            <div class="row">
              <!-- Forma para contacto con nosotros.-->
              <form class="col s12" name="contactosegunda"  method="post">{% csrf_token %}
                <div class="row">
                  <input name="titulo_segunda" type="text" value="{{ segunda.titulo }}" hidden>
                  <input name="contenido_segunda" type="text" value="{{ segunda.contenido }}" hidden>
                  <input name="precio_segunda" type="text" value="{{ segunda.precio }}" hidden>
                  <input name="llave_segunda" type="number" value="{{ segunda.pk }}" hidden>
                  <div class="input-field col s5 offset-s1 text_login">
                    <i class="material-icons prefix">account_circle</i>
                    {{formseg.nombre_segunda}}
                    <label for="nombre_contacto">Nombre</label>
                  </div>
                  <div class="input-field col s5 text_login">
                    {{formseg.apellido_segunda}}
                    <label for="apellido_contacto">Apellidos</label>
                  </div>
                </div>
                <div class="row">
                    <div class="input-field col s10 offset-s1">
                      <i class="material-icons prefix">phone</i>
                      {{formseg.telefono_segunda}}
                      <label for="telefono_segunda">Teléfono</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s10 offset-s1">
                       <i class="material-icons prefix">mail</i>
                      {{formseg.email_segunda}}
                      <label for="email_contacto">Email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s10 offset-s1">
                      {{formseg.textarea_segunda}}
                      <label for="textarea_contacto">Observaciones</label>
                    </div>
                </div>
                <div class="row">
                  <div class="input-field col s4 offset-s4">
                  <button id="buttsubmit" class="waves-effect waves-light btn-flat modal-trigger"
                   type="submit" name="action">Enviar
                     <i class="material-icons right">send</i>
                  </button>
                 </div>
                </div>
              </form>
            </div>
          </div>
          <div class="modal-footer">
            <a class="modal-action modal-close waves-effect waves-green btn-flat">Cerrar</a>
          </div>
        </div>
      </div>
      </div>
      </div>
  {% if forloop.first == true or forloop.counter|divisibleby:3 %}
   </div>
  {% endif %}
{% endfor %}

segundasapp/templates/segundasapp/google5a135354c3e98127.html
google-site-verification: google5a135354c3e98127.html

segundasapp/templates/segundasapp/index.html
{% extends "segundasapp/base.html" %}
{% load staticfiles %}
{% load static %}
{% block slick_script %}
  <link rel="stylesheet" type="text/css"  href="{% static 'segundasapp/css/slick.css' %}" />
  <link rel="stylesheet" type="text/css"  href="{% static 'segundasapp/css/slick-theme.css' %}" />
  <script type="text/javascript" src="{% static 'segundasapp/js/slick.min.js' %}"></script>
{% endblock slick_script %}
{% block slider_script %}
<script type="text/javascript" src="{% static 'segundasapp/js/sliders.js' %}"></script>
{% endblock slider_script %}
{% block pushpan_script %}
<script type="text/javascript" src="{% static 'segundasapp/js/pushpan.js' %}"></script>
{% endblock pushpan_script %}

 {% block index_content %}
<div id="para1" class="parallax-container">
 <div class="section no-pad-bot" style="top:10px;">
   <div class="container">
     <div class="row">
       <div class="col l4 hide-on-med-and-down" style="margin-top:5%;">
         <h1 >segundas.mx</h1>
       </div>
       <div class="col l6 m12 s12 offset-l2">
       <h5 class="col l12 light logoblue" style="text-align: justify;
       text-justify: inter-word;border-radius:7px;">
         Somos una empresa dedicada a la compra-venta de distintos productos
         de acero de segunda con el objetivo de cubrir las necesidades de los
         diferentes tipos de proyectos. Nuestra experiencia nos permite brindar
         un servicio de calidad y valor para nuestros clientes, garantizando
         así una atención eficaz, cálida y puntual, ya sea que quiera compra
         o vender.
       </h5>
      </div>
     </div>
   </div>
 </div>
 <div class="parallax"><img src="{% static 'segundasapp/images/segundasfondo1.jpg' %}"
   style="width:100%;"
alt="Unsplashed background img 1"></div>
</div>
<div class="row">
  <div class="col s12 m4">
    <div class="icon-block">
      <h2 class="center blue-grey-text"><i class="material-icons">assignment_ind</i></h2>
       <a href ="{% url 'index'%}"><h5 class="center">Quiénes somos</h5></a>

      <p class="light center">Empresa mexicana dedidacada a la
       compra-venta de segundas de acero y materiales de construcción.</p>
    </div>
  </div>
  <!-- azul_icono -->
  <div class="col s12 m4">
    <div class="icon-block">
      <h2 class="center blue-grey-text"><i class="material-icons">group</i></h2>
      <a href ="{% url 'venta_segundas'%}"><h5 class="center">Compra de segundas</h5> </a>

      <p class="light center"> Ve nuestras excelentes ofertas de segundas</p>
    </div>
  </div>

  <div class="col s12 m4">
    <div class="icon-block">
      <h2 class="center blue-grey-text"><i class="material-icons">money</i></h2>
       <a href ="{% url 'contacto'%}"><h5 class="center">Véndenos tus segundas</h5></a>
      <p class="light center">Compramos a los precios más justos</p>
    </div>
  </div>
</div>

<div id="smaltblue" class="block">
  <div class="nav-wrapper" style="height:64px;">
  <nav class="pushpin-demo-nav pin-top" data-target="smaltblue" style="top: 0px;">
    <div class="nav-wrapper smaltblue " style="height:64px;">
      <div class="container">
        <a href="{% url 'contacto'%}" class="brand-logo center turquesa-text hide-on-med-and-down">Compramos tus segundas</a>
      </div>
    </div>
  </nav>
</div>
<div id="index-banner" class="parallax-container">
 <div class="section no-pad-bot" style="top:0px;bottom:0px;">
   <div class="container">
     <div class="row" style="margin-top:10%;">
       <div class="col l4 m4 s4">
       <image src = "{% static 'segundasapp/images/background1.png' %}" width="100%"
       height="100%" href="{% url 'index'%}" style="border-radius:7px;border-style: solid;
     border-width: 1px;border-color: #587291;" >
     </div>
     <div class="col l4 m4 s4">
     <image src = "{% static 'segundasapp/images/background2.png' %}" width="100%"
     height="100%" href="{% url 'index'%}" style="border-radius:7px;border-style: solid;
   border-width: 1px;border-color: #587291;" >
   </div>
   <div class="col l4 m4 s4">
     <image src = "{% static 'segundasapp/images/background3.png' %}" width="100%"
     height="100%" href="{% url 'index'%}" style="border-radius:7px;border-style: solid;
   border-width: 1px;border-color: #587291;" >
 </div>
     </div>
     <div class="row">
       <div class="col l12 m12 s12" style="border-radius:7px;">
         <h5 class="light turquesa uclablue-text" style="text-align: justify;
         text-justify: inter-word;margin-top:5%;border-radius:7px;">
           En <span style="font-weight:bold;">
           segundas.mx</span> compramos todos los materiales de construcción que te sobren:
           desde varillas, malla electrosoldada, alambrón, hasta ladrillos y vigas. Aceros,
           metales, cemento, grava... Sólo envíanos tu información y en seguida te contactaremos.
         </h5>
           <div class="col l4 m12 s12 offset-l4" >
             <a href="{% url 'contacto'%}" class="waves-effect waves-light btn"><i class="material-icons left" style="z-index:40;">
               cloud</i>Vende tus segundas</a>
           </div>
       </div>
   </div>
 </div>
 <div class="parallax"><img src="{% static 'segundasapp/images/solera.jpg' %}"
   style="width:100%;bottom:0px;"
alt="Unsplashed background img 1"></div>
</div>
</div>
</div>

<div id="logoblue" class="block">
  <div class="nav-wrapper" style="height:64px;">
  <nav class="pushpin-demo-nav pin-top" data-target="logoblue" style="top:0px;height:64px;">
    <div class="nav-wrapper logoblue hide-on-med-and-down" style="height:64px;">
      <div class="container">
        <a href="{% url 'venta_segundas'%}" class="brand-logo center hide-on-med-and-down">Vendémos segundas</a>
      </div>
    </div>
  </nav>
</div>
<div id="index-banner" class="parallax-container">
 <div class="section no-pad-bot" style="top:0px;">
   <div class="container">
     <div class="row" >
       <div class="col l12" style="border-radius:7px;">
         <h5 class="light uclablue white-text" style="text-align: justify;
         text-justify: inter-word;margin-top:3%;border-radius:7px;">
           Visita nuestro mercado de segundas y material de construcción.Visualiza los
           materiales y contactanos para  obtener los mejores materiales a los mejores precios!
         </h5>
       </div>
     </div>
     <div class="row uclablue" style="border-width:1px;border-radius:7px;
     border-color:#587291;">
     <div class="col l12">
       <h5>Últimas ofertas:</h5>
     </div>
         <div class="col l12 hide-on-med-and-down">
         <div id="segundas">
           {% for segunda in segundas %}
                 <div class="col l4 m4 s12">
                   <div class="card">
                     <div class="card-image" style="margin-bottom:1px;">
                       <!-- Aqui empieza carrusel -->
                        <a class="btn-floating halfway-fab waves-effect waves-light modal-trigger columbiablue" href="{% url 'venta_segundas'%}">
                          <i class="material-icons">add</i></a>
                     </div>
                     <div class="card-stacked">
                     <div class="card-content black-text" style="padding:0px;margin-left:10px;">
                     <h6 style="font-weight:bold;"> {{ segunda.get_categoria_display }} </h6>
                     <h6 style="font-weight:bold;">{{ segunda.titulo }}</h6>
                     <h6>{{ segunda.fecha }}</h6>
                     <h6>{{ segunda.precio }}</h6>
                     <br>
                     <br>
                   </div>
                 </div>
                 </div>
                 </div>
           {% endfor %}
      </div>
    </div>
    <div class="col l4 offset-l4">
      <a href="{% url 'venta_segundas'%}"><h5 class="bold white-text">Ir a mercado de segundas</h5></a>
    </div>
       </div>
     <div class="row" style="margin-top:5%;">
     </div>
 </div>
 <div class="parallax"><img src="{% static 'segundasapp/images/placa-acer-segunda.jpg' %}"
   style="width:100%;"
alt="Unsplashed background img 1"></div>
</div>
</div>
</div>
 {% endblock index_content %}